# Generated by Django 5.0.4 on 2025-03-09 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
